### ISSUE TITLE
Update CinImageViewer to use the new DBView architecture

### ISSUE THREAD

**Issue by dhrogers** [cinemascience/cinema_scope#12]
For the new object architecture, CinImageViewer should not have to use any DB queries, and instead should use the CinDBView object and its CinParamSet and CinArtifactSet member variables in the same way that CinParamSliders does now.

The code now runs so that CinParamSliders use the proper mechanism. CinImageViewer has been updated to be connected to the new update signal (in mainwindow.cpp).

I'll continue to update the documentation to show how this should work, but stop by if you have any questions and want to get started.

**Comment by dhrogers** [comment]
![class_diagram](https://user-images.githubusercontent.com/5340672/49168460-c4a6ae00-f2f4-11e8-8415-3efe46c7d6b0.png)

**Comment by dhrogers** [comment]
See the usage diagram above. Most of the activity should be through the CinParamSet object. The artifactChanged(...) signal is already connected to the CinImageViewer object in mainwindow.cpp

**Comment by mindbender12** [comment]
This is also done I think.

**Comment by dhrogers** [comment]
Complete.
