### ISSUE TITLE
Add QPixmapCache to CinImageViewer to optimize loading and interaction

### ISSUE THREAD

**Issue by dhrogers** [cinemascience/cinema_scope#13]

**Comment by dhrogers** [comment]
@mindbender12 : would like to do code review of this. Still not sure this isn't one big memory leak, with the mechanism of loading into the graphics scene.

This new mechanism duplicates the existing mechanism, so it's no worse than what we have currently, and it includes the caching of images.

**Comment by dhrogers** [comment]
This has been implemented. Awaiting review.

**Comment by mindbender12** [comment]
I will look into this and let you know.

**Comment by dhrogers** [comment]
Complete
