### ISSUE TITLE
Implement mouse interaction for image window

### ISSUE THREAD

**Issue by dhrogers** [cinemascience/cinema_scope#2]
Mouse drags in the image window should map to parameters in the loaded cinema databse. By default, this should map to "phi" and "theta', but the mapping should be overwritable by the application.

**Comment by mindbender12** [comment]
Thanks, I looked at it and it looks great. This will be helpful.

**Comment by dhrogers** [comment]
Currently works, but it needs to be adjusted so that it begins immediately (right now there is a lag in interaction), and scaled to take into account the number of items in the parameter that is being manipulated.

**Comment by dhrogers** [comment]
allow user to set parameter that controls an action. Actions:

Horizontal drag
Vertical drag
Shift + Horizontal drag

**Comment by dhrogers** [comment]
Complete. Awaiting user feedback on operation.
