### ISSUE TITLE
Vertical drag in window goes backwards

### ISSUE THREAD

**Issue by dhrogers** [cinemascience/cinema_scope#23]
File->Open unittesting/test_cylinder.cbd opens a test database of a cylinder. Dragging vertical/horizontal in the window spins things in the wrong direction.

**Comment by mindbender12** [comment]
Will look into this bug.

**Comment by mindbender12** [comment]
Have a fix for the bug. Please test and let me know if it does not work.

**Comment by terryturton** [comment]
Yes, it works now.
