### ISSUE TITLE
Test mac installer at https://cinemascience.github.io/cinema_scope/

### ISSUE THREAD

**Issue by dhrogers** [cinemascience/cinema_scope#24]
Test Mac installer on a 'clean' machine (on without Qt installed). I expect this to work on OSX High SIerra and later (10.13.x)

This is a test of the mac installer creation process at this point. The installer needs some work (in particular, it doesn't install in the Applications directory, but this is a first pass).

To test:

1. Go to https://cinemascience.github.io/cinema_scope
2. Download the mac installer (click the link); install in some directory
3. Download the test data set (click the link)
4. Double click on the mac installer (CinemaScopeInstaller001.dmg) and follow instructions
5. Open CinemaScope after it's installed, and open the test data set.

Report here on any problems.

**Comment by terryturton** [comment]
I don't have a clean (no Qt) machine right now.  I should be able to test later this week.  It works on my LANL machine.  

Need to add between 4 & 5 to edit the .cinema/scope/setting.ini file to point to the directory where the test data is located.

**Comment by mindbender12** [comment]
It will be hard for me to test it on  Mac since I do not have other machines or the OS installer. I can try it on Linux later this week within a virtual machine if that helps. Let me know.

**Comment by dhrogers** [comment]
Complete
