### ISSUE TITLE
Large number of parameter values (time steps) causes issue 

### ISSUE THREAD

**Issue by terryturton** [cinemascience/cinema_scope#27]
Using an MPAS database with 173 time steps, the image artifacts are not linked properly to the parameter slider.  Note that editing the parameters and linking it to the the mouse movement correctly scrolls through the images.   The data.csv (as data.txt) is attached.  

[data.txt](https://github.com/cinemascience/cinema_scope/files/2674032/data.txt)

**Comment by dhrogers** [comment]
Checked in fix for this bug. I tested it against an automatically generated dataset that showed the same behavior.

To generate the test dataset, go to unittesting, run the create_database script. It will create a test.cdb dataset that shows the same behavior.

Please test with the time dataset - I don't have the images for that (not checked into repo).

**Comment by dhrogers** [comment]
On closer look, I think this was a bug in having parameters that were increasing by one - a set like [1,2,3,4,5,6,7,8,9 ...] - due to the search function. I'll have to take a look at it to be sure.

**Comment by terryturton** [comment]
Tested with MPAS 173 time steps, increasing by 1, time is now functional on the slider.
Tested with FleCSPH 6 time steps, increasing by 1, time is now functional on the slider.
