### ISSUE TITLE
Add cinema_scope_test build to travis build scripts

### ISSUE THREAD

**Issue by dhrogers** [cinemascience/cinema_scope#33]
In addition to building the cinema_scope_test.pro project, the travis build script should build the cinema_scope_test.pro project, which is the unit testing.

Looking at the output from the travis builds from my last checkin, it appears that this isn't happening, but I could be wrong.

**Comment by dhrogers** [comment]
Sorry - typo above. The two projects that build should be cinema_scope.pro, and if that passes, cinema_scope_test.pro

**Comment by camtauxe** [comment]
I have a commit that I think fixes this on my own fork at the moment, but I can't test the OSX builds because of a problem on Travis's end (which I mentioned here #35 )

**Comment by dhrogers** [comment]
This is working.
