### ISSUE TITLE
Travis now failing all OSX builds

### ISSUE THREAD

**Issue by camtauxe** [cinemascience/cinema_scope#35]
This seems to be a problem on Travis's end. All OSX builds are now failing when updating homebrew. I know it isn't a change we made because I even tried re-running builds that were previously successful but now fail. I don't think there is anything we can do about it until Travis fixes it, but I figured I should at least document the issue here.

**Comment by dhrogers** [comment]
Thanks, Cameron. I noticed this today. At first, all builds were failing, but now it looks like the LInux ones are fixed. Assuming they will fix the OSX as well.

Thanks for documenting this.

**Comment by camtauxe** [comment]
Thanks Ethan! I merged in your commit and it works now. I'll close this issue for now.
