### ISSUE TITLE
redesign CinImageView to use simpler parameter manipulation

### ISSUE THREAD

**Issue by dhrogers** [cinemascience/cinema_scope#39]
CinImageView's mouse move operations should simply 'increment' and 'decrement' parameter values, instead of the current methods. There are now two calls in CinParamSet that should be used:

CinParamSet::increment( paramName );
CinParamSet::decrement( paramName );

Currently the mouse drag code is commented out, because we are redesigning other aspects of parameters.

**Comment by mindbender12** [comment]
I have pushed a version of code which uses 'increment' and 'decrement' operation while mouse dragging takes place. I have done some testing and it seems to work correctly. Please test and let me know if it has issues.

**Comment by terryturton** [comment]
@mindbender12 @dhrogers 
I have also tested with a range of CDBs and it behaves as expected.  Closing issue.
